application: control-space
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /?
  static_files: index.html
  upload: index.html

- url: /2016/03/.*/(.*[^/]$)
  static_files: 2016/03/\1/index.html
  upload: (.*)

- url: /2016/03/.*/(.*)/$
  static_files: 2016/03/\1/index.html
  upload: (.*)

- url: /sitemap(.xml)?
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /atom(.xml)?
  static_files: atom.xml
  upload: atom.xml

- url: /tag/(.*[^/]$)
  static_files: tags/\1/index.html
  upload: (.*)

- url: /tag/(.*)/$
  static_files: tags/\1/index.html
  upload: (.*)

- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|txt|xml|js|min).*)
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|txt|xml|js|min))

- url: /(.+[^/])/index.html
  static_files: \1/index.html
  upload: (.*)

- url: /(.+[^/]$)
  static_files: \1/index.html
  upload: (.*)

- url: /(.+)/
  static_files: \1/index.html
  upload: (.*)

skip_files:
- ^(node_modules/.*)
- ^(scaffolds/.*)
- ^(source/.*)
- ^(themes/.*)
- ^(.git/.*)
- ^(.*/)?.DS_Store$

libraries:
- name: webapp2
  version: "2.5.2"
