application: control-space
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#root
- url: /?
  static_files: index.html
  upload: index.html

- url: /m/?
  static_files: index.html
  upload: index.html

- url: /mobile/?
  static_files: index.html
  upload: index.html

- url: /sitemap(.xml)?
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /atom(.xml)?
  static_files: atom.xml
  upload: atom.xml

- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|xml|txt|js|min\.js))/?
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|xml|txt|js|min.\js))

- url: /(.+[^/]$)
  static_files: \1/index.html
  upload: (.*)

- url: /(.+)/
  static_files: \1/index.html
  upload: (.*)

skip_files:
- ^(node_modules/.*)
- ^(scaffolds/.*)
- ^(source/.*)
- ^(themes/.*)
- ^(.git/.*)
- ^(.*/)?.DS_Store$

libraries:
- name: webapp2
  version: "2.5.2"
